### ISSUE TITLE
Optimistic concurrency

### ISSUE THREAD

**Issue by florianbepunkt** [oskardudycz/EventSourcing.NodeJS#16]
I like the way you explain things. I see there are some open PRs, including one about optimistic concurrency and commands. It would be great if you could also add explanations to the README for these concepts. This repo is a fantastic learning resource. Thank you.

**Comment by oskardudycz** [comment]
Thank you @florianbepunkt. In fact, getting the README to the proper state is the reason why I didn't merge them yet 😓 

But I have articles on those topics on my blog, have a look on:
- https://event-driven.io/en/how_to_use_etag_header_for_optimistic_concurrency/
- https://event-driven.io/en/dealing_with_eventual_consistency_and_idempotency_in_mongodb_projections/

I hope that I'll be able to finish them soon!
